#!/bin/bash
# iptables rule template
# Generated by AI Firewall Rule-Miner

iptables -A INPUT {{ source_spec }} {{ destination_spec }} {{ protocol_spec }} {{ port_spec }} {{ time_spec }} -j {{ action }} {{ comment_spec }}
