# Windows Advanced Firewall PowerShell template
# Generated by AI Firewall Rule-Miner

New-NetFirewallRule -DisplayName "{{ name }}" -Direction Inbound -Action {{ action }} {{ protocol_spec }} {{ port_spec }} {{ address_spec }} -Description "{{ description }}"
